"""empty message

Revision ID: 011f3f076c88
Revises: e1fa0dadccfb
Create Date: 2017-02-23 00:19:14.481918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011f3f076c88'
down_revision = 'e1fa0dadccfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosts', sa.Column('firstName', sa.String(length=120), nullable=True))
    op.drop_column('hosts', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosts', sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('hosts', 'firstName')
    # ### end Alembic commands ###
