"""empty message

Revision ID: 085df48bf96c
Revises: 75ac6b3bc691
Create Date: 2017-02-22 23:48:27.975194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '085df48bf96c'
down_revision = '75ac6b3bc691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_rep', sa.Column('totalEmailsReviewedByHumans', sa.Integer(), nullable=True))
    op.drop_column('sales_rep', 'totalEmailsReviewedByHomans')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_rep', sa.Column('totalEmailsReviewedByHomans', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('sales_rep', 'totalEmailsReviewedByHumans')
    # ### end Alembic commands ###
