"""empty message

Revision ID: 0e25d532dbb5
Revises: 762194aeb0a3
Create Date: 2017-03-08 20:27:52.056820

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0e25d532dbb5'
down_revision = '762194aeb0a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_rep', sa.Column('workHours', postgresql.JSON(), nullable=True))
    op.drop_column('sales_rep', 'dayEnd')
    op.drop_column('sales_rep', 'dayStart')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_rep', sa.Column('dayStart', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('sales_rep', sa.Column('dayEnd', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('sales_rep', 'workHours')
    # ### end Alembic commands ###
