"""empty message

Revision ID: 1c3428e4c417
Revises: c24233b26167
Create Date: 2017-02-21 23:56:26.642125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c3428e4c417'
down_revision = 'c24233b26167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_rep', sa.Column('dayEnd', sa.DateTime(), nullable=True))
    op.add_column('sales_rep', sa.Column('dayStart', sa.DateTime(), nullable=True))
    op.add_column('sales_rep', sa.Column('hostName', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_rep', 'hostName')
    op.drop_column('sales_rep', 'dayStart')
    op.drop_column('sales_rep', 'dayEnd')
    # ### end Alembic commands ###
