"""empty message

Revision ID: 1d588479353d
Revises: 74ca6623beaa
Create Date: 2017-02-21 11:31:51.324030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d588479353d'
down_revision = '74ca6623beaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'leads_email_key', 'leads', type_='unique')
    op.drop_constraint(u'leads_threadId_key', 'leads', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'leads_threadId_key', 'leads', ['threadId'])
    op.create_unique_constraint(u'leads_email_key', 'leads', ['email'])
    # ### end Alembic commands ###
