"""empty message

Revision ID: 29b19747babf
Revises: 304dd1e4b032
Create Date: 2017-03-05 16:10:31.375775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '29b19747babf'
down_revision = '304dd1e4b032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salesRepId', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('firstName', sa.String(length=120), nullable=True),
    sa.Column('company', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('callTime', sa.DateTime(), nullable=True),
    sa.Column('interest', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['salesRepId'], ['sales_rep.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'lead_threads', sa.Column('gThreadId', sa.String(length=120), nullable=True))
    op.add_column(u'lead_threads', sa.Column('leadId', sa.Integer(), nullable=True))
    op.drop_constraint(u'lead_threads_salesRep_fkey', 'lead_threads', type_='foreignkey')
    op.create_foreign_key(None, 'lead_threads', 'leads', ['leadId'], ['id'])
    op.drop_column(u'lead_threads', 'status')
    op.drop_column(u'lead_threads', 'firstName')
    op.drop_column(u'lead_threads', 'salesRep')
    op.drop_column(u'lead_threads', 'company')
    op.drop_column(u'lead_threads', 'callTime')
    op.drop_column(u'lead_threads', 'phone')
    op.drop_column(u'lead_threads', 'interest')
    op.drop_column(u'lead_threads', 'threadId')
    op.drop_column(u'lead_threads', 'email')
    op.add_column(u'sales_rep', sa.Column('pollingError', sa.Integer(), nullable=True))
    op.drop_column(u'sales_rep', 'totalCallsScheduled')
    op.drop_column(u'sales_rep', 'totalLeadsManaged')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'sales_rep', sa.Column('totalLeadsManaged', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(u'sales_rep', sa.Column('totalCallsScheduled', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column(u'sales_rep', 'pollingError')
    op.add_column(u'lead_threads', sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column(u'lead_threads', sa.Column('threadId', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column(u'lead_threads', sa.Column('interest', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(u'lead_threads', sa.Column('phone', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column(u'lead_threads', sa.Column('callTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column(u'lead_threads', sa.Column('company', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column(u'lead_threads', sa.Column('salesRep', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column(u'lead_threads', sa.Column('firstName', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column(u'lead_threads', sa.Column('status', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lead_threads', type_='foreignkey')
    op.create_foreign_key(u'lead_threads_salesRep_fkey', 'lead_threads', 'sales_rep', ['salesRep'], ['email'])
    op.drop_column(u'lead_threads', 'leadId')
    op.drop_column(u'lead_threads', 'gThreadId')
    op.drop_table('leads')
    # ### end Alembic commands ###
