"""empty message

Revision ID: 39c9dde866d4
Revises: aae92f483221
Create Date: 2017-03-14 00:05:32.581462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '39c9dde866d4'
down_revision = 'aae92f483221'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_rep', sa.Column('connectedAccounts', postgresql.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_rep', 'connectedAccounts')
    # ### end Alembic commands ###
