"""empty message

Revision ID: 41b2c3b2efaa
Revises: 29b19747babf
Create Date: 2017-03-06 12:34:04.208063

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '41b2c3b2efaa'
down_revision = '29b19747babf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hosts', 'calendars')
    op.drop_column('hosts', 'salesRep')
    op.drop_column('hosts', 'callDuration')
    op.drop_column('hosts', 'salesRepName')
    op.drop_column('hosts', 'dayEnd')
    op.drop_column('hosts', 'salesRepSignature')
    op.drop_column('hosts', 'dayStart')
    op.add_column('sales_rep', sa.Column('calendars', postgresql.JSON(), nullable=True))
    op.add_column('sales_rep', sa.Column('callDuration', sa.Integer(), nullable=True))
    op.add_column('sales_rep', sa.Column('dayEnd', sa.DateTime(), nullable=True))
    op.add_column('sales_rep', sa.Column('dayStart', sa.DateTime(), nullable=True))
    op.add_column('sales_rep', sa.Column('hostId', sa.Integer(), nullable=True))
    op.add_column('sales_rep', sa.Column('monitorEmail', sa.Boolean(), nullable=True))
    op.drop_constraint(u'sales_rep_hostEmail_fkey', 'sales_rep', type_='foreignkey')
    op.create_foreign_key(None, 'sales_rep', 'hosts', ['hostId'], ['id'])
    op.drop_column('sales_rep', 'hostEmail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_rep', sa.Column('hostEmail', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sales_rep', type_='foreignkey')
    op.create_foreign_key(u'sales_rep_hostEmail_fkey', 'sales_rep', 'hosts', ['hostEmail'], ['email'])
    op.drop_column('sales_rep', 'monitorEmail')
    op.drop_column('sales_rep', 'hostId')
    op.drop_column('sales_rep', 'dayStart')
    op.drop_column('sales_rep', 'dayEnd')
    op.drop_column('sales_rep', 'callDuration')
    op.drop_column('sales_rep', 'calendars')
    op.add_column('hosts', sa.Column('dayStart', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('hosts', sa.Column('salesRepSignature', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('hosts', sa.Column('dayEnd', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('hosts', sa.Column('salesRepName', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('hosts', sa.Column('callDuration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('hosts', sa.Column('salesRep', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('hosts', sa.Column('calendars', postgresql.JSON(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
