"""empty message

Revision ID: 48334235b78d
Revises: 
Create Date: 2017-02-19 20:22:45.669458

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '48334235b78d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_rep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('hostEmail', sa.String(length=120), nullable=True),
    sa.Column('firstName', sa.String(length=120), nullable=True),
    sa.Column('company', sa.String(length=120), nullable=True),
    sa.Column('labelIds', postgresql.JSON(), nullable=True),
    sa.Column('signature', sa.TEXT(), nullable=True),
    sa.Column('latestHistoryId', sa.String(length=120), nullable=True),
    sa.Column('hasUpdate', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('spreadSheetId', sa.String(length=120), nullable=True),
    sa.Column('calendlyUrl', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salesRep', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('firstName', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('callTime', sa.DateTime(), nullable=True),
    sa.Column('interest', sa.Integer(), nullable=True),
    sa.Column('review', sa.Boolean(), nullable=True),
    sa.Column('reviewReason', sa.TEXT(), nullable=True),
    sa.Column('subject', sa.TEXT(), nullable=True),
    sa.Column('threadId', sa.String(length=120), nullable=True),
    sa.Column('msgIds', sa.TEXT(), nullable=True),
    sa.Column('conversationText', sa.TEXT(), nullable=True),
    sa.Column('sentEmailCount', sa.Integer(), nullable=True),
    sa.Column('replyEmailCount', sa.Integer(), nullable=True),
    sa.Column('lastEmailSentTime', sa.DateTime(), nullable=True),
    sa.Column('lastEmailReceivedTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['salesRep'], ['sales_rep.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('threadId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leads')
    op.drop_table('users')
    op.drop_table('sales_rep')
    # ### end Alembic commands ###
