"""empty message

Revision ID: 503deea47cd9
Revises: 39c9dde866d4
Create Date: 2017-03-14 00:23:48.323871

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '503deea47cd9'
down_revision = '39c9dde866d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_rep', 'calendars')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_rep', sa.Column('calendars', postgresql.JSON(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
