"""empty message

Revision ID: 52eba4f06ee0
Revises: ba6d49f167ab
Create Date: 2017-02-26 17:44:11.110410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52eba4f06ee0'
down_revision = 'ba6d49f167ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('latestReply', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'latestReply')
    # ### end Alembic commands ###
