"""empty message

Revision ID: 762194aeb0a3
Revises: c7cdcf7845d7
Create Date: 2017-03-08 03:57:27.951169

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '762194aeb0a3'
down_revision = 'c7cdcf7845d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('entities', postgresql.JSON(), nullable=True))
    op.drop_column('leads', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('data', postgresql.JSON(), autoincrement=False, nullable=True))
    op.drop_column('leads', 'entities')
    # ### end Alembic commands ###
