"""empty message

Revision ID: 77e63f76c760
Revises: 86a7bb1b7c39
Create Date: 2017-02-23 16:17:36.030994

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '77e63f76c760'
down_revision = '86a7bb1b7c39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('receivedEmailCount', sa.Integer(), nullable=True))
    op.drop_column('leads', 'replyEmailCount')
    op.create_foreign_key(None, 'sales_rep', 'hosts', ['hostEmail'], ['email'])
    op.drop_column('sales_rep', 'labelIds')
    op.drop_column('sales_rep', 'hasUpdate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_rep', sa.Column('hasUpdate', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('sales_rep', sa.Column('labelIds', postgresql.JSON(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sales_rep', type_='foreignkey')
    op.add_column('leads', sa.Column('replyEmailCount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('leads', 'receivedEmailCount')
    # ### end Alembic commands ###
