"""empty message

Revision ID: 86a7bb1b7c39
Revises: 011f3f076c88
Create Date: 2017-02-23 12:11:32.006007

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '86a7bb1b7c39'
down_revision = '011f3f076c88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosts', sa.Column('calendars', postgresql.JSON(), nullable=True))
    op.drop_column('hosts', 'hostCalendar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosts', sa.Column('hostCalendar', postgresql.JSON(), autoincrement=False, nullable=True))
    op.drop_column('hosts', 'calendars')
    # ### end Alembic commands ###
