"""empty message

Revision ID: 99e6779ad630
Revises: 0e25d532dbb5
Create Date: 2017-03-09 11:45:45.891324

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '99e6779ad630'
down_revision = '0e25d532dbb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_rep', 'compulsoryFormFields')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_rep', sa.Column('compulsoryFormFields', postgresql.JSON(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
