"""empty message

Revision ID: aae92f483221
Revises: f8674c143563
Create Date: 2017-03-13 12:14:11.952538

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aae92f483221'
down_revision = 'f8674c143563'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_rep', 'integrations')
    op.add_column('sales_rep',sa.Column('spreadSheetId', sa.String(length=120), nullable=True))
    op.add_column('sales_rep',sa.Column('webHookUrl', sa.String(length=120), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_rep', sa.Column('integrations', postgresql.JSON(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
