"""empty message

Revision ID: ba6d49f167ab
Revises: 77e63f76c760
Create Date: 2017-02-26 14:01:21.572077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba6d49f167ab'
down_revision = '77e63f76c760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('company', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'company')
    # ### end Alembic commands ###
