"""empty message

Revision ID: c24233b26167
Revises: 4ebf267cf6c3
Create Date: 2017-02-21 20:50:16.775976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c24233b26167'
down_revision = '4ebf267cf6c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_rep', sa.Column('callDuration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_rep', 'callDuration')
    # ### end Alembic commands ###
