"""empty message

Revision ID: c7cdcf7845d7
Revises: d2d6e1b48e4b
Create Date: 2017-03-06 17:09:02.886878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7cdcf7845d7'
down_revision = 'd2d6e1b48e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_rep', sa.Column('spreadSheetId', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_rep', 'spreadSheetId')
    # ### end Alembic commands ###
