"""empty message

Revision ID: d2d6e1b48e4b
Revises: f13e9f8b5f75
Create Date: 2017-03-06 16:35:13.364358

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd2d6e1b48e4b'
down_revision = 'f13e9f8b5f75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_rep', sa.Column('compulsoryFormFields', postgresql.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_rep', 'compulsoryFormFields')
    # ### end Alembic commands ###
