"""empty message

Revision ID: d87a7172a7ea
Revises: 99e6779ad630
Create Date: 2017-03-11 20:39:35.343536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd87a7172a7ea'
down_revision = '99e6779ad630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_rep', sa.Column('compulsoryFields', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_rep', 'compulsoryFields')
    # ### end Alembic commands ###
