"""empty message

Revision ID: debf867895ae
Revises: 503deea47cd9
Create Date: 2017-03-19 10:07:32.893678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'debf867895ae'
down_revision = '503deea47cd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'sales_rep_hostId_fkey', 'sales_rep', type_='foreignkey')
    op.drop_column('sales_rep', 'hostId')
    op.drop_table('hosts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_rep', sa.Column('hostId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'sales_rep_hostId_fkey', 'sales_rep', 'hosts', ['hostId'], ['id'])
    op.create_table('hosts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('firstName', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('company', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('authenticated', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('registered_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'hosts_pkey')
    )
    # ### end Alembic commands ###
