"""empty message

Revision ID: e1fa0dadccfb
Revises: 085df48bf96c
Create Date: 2017-02-23 00:15:15.384120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1fa0dadccfb'
down_revision = '085df48bf96c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosts', sa.Column('company', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hosts', 'company')
    # ### end Alembic commands ###
