"""empty message

Revision ID: ec03e6777c26
Revises: 48334235b78d
Create Date: 2017-02-20 16:20:22.312709

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ec03e6777c26'
down_revision = '48334235b78d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_rep', sa.Column('templates', postgresql.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_rep', 'templates')
    # ### end Alembic commands ###
