"""empty message

Revision ID: f13e9f8b5f75
Revises: 41b2c3b2efaa
Create Date: 2017-03-06 15:56:09.928833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f13e9f8b5f75'
down_revision = '41b2c3b2efaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('data', postgresql.JSON(), nullable=True))
    op.add_column('sales_rep', sa.Column('qualify', postgresql.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_rep', 'qualify')
    op.drop_column('leads', 'data')
    # ### end Alembic commands ###
