"""empty message

Revision ID: f8674c143563
Revises: d87a7172a7ea
Create Date: 2017-03-13 00:27:07.968555

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'f8674c143563'
down_revision = 'd87a7172a7ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_rep', 'spreadSheetId')
    op.add_column('sales_rep',sa.Column('integrations',postgresql.JSON(),nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_rep', sa.Column('spreadSheetId', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
